var net = require("net");
var server = net.createServer();
var dotenv = require('dotenv');
var fs = require('fs');
var cloudinary = require('cloudinary').v2;
dotenv.load();

var uploads = {};

server.on("connection", function(socket) {
  var remoteAddress = socket.remoteAddress + ":" + socket.remotePort;
  console.log("new client connection is made");

  socket.on("data", function (d) {
    console.log("Data from ", remoteAddress, d);

    // set your env variable CLOUDINARY_URL or set the following configuration
    cloudinary.config({
      cloud_name: 'dhfy626bo',
      api_key: '622975299212492',
      api_secret: 'McutiJ7Kr_5QTh05SSkQC28ymtw'
    });

    console.log( "** ** ** ** ** ** ** ** ** Uploads ** ** ** ** ** ** ** ** ** **");
    // File upload
    cloudinary.uploader.upload("C:\\Users\\재기\\Desktop\\hbi\\face\\test.jpg", {tags:'basic_sample'},function(err,image){
      console.log("** File Upload");
      if (err){ console.warn(err);}
      console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
      console.log("* "+image.public_id);
      console.log("* "+image.url);
      var temp = image.url;

      socket.write(temp);
    });
  });
  socket.once("close", function () {
    console.log("connection closed");
  });
  socket.on("error", function(err) {
    console.log("error");
  });
});

server.listen(9000, function () {
  console.log("server listening to %j", server.address());
});
